### ISSUE TITLE
Could not find the document.

### ISSUE THREAD

**Issue by caspervonb** [jekyll/jekyll-admin#184]
When trying to edit a collection document, I get an error saying "Could not find the document".

## Versions
```console
gem list --local | grep jekyll-admin
jekyll (3.1.6)
jekyll-admin (0.1.0)
```

Listing and viewing the collection works fine.

The collection is just defined as
```yaml
collections:
  tutorials:
    output: true
```
