### ISSUE TITLE
front matter defaults not applied to collection posts

### ISSUE THREAD

**Issue by ecupaio** [jekyll/jekyll-admin#275]
Here's my _config.yml
```
collections:
  bios:
    output: true
    permalink: /bios/:path/
  chapters:
    output: true
defaults:
  -
    scope:
      path: "bios"
      type: "bios"
    values:
      layout: "bios"
```
When I look at any of my bios posts or create new bios posts, the front matter default `layout: "bios"` is not in the md file nor is it visible in the admin interface. What's the deal?
