### ISSUE TITLE
Ability to change /admin and /_api paths

### ISSUE THREAD

**Issue by JohannesMP** [jekyll/jekyll-admin#435]
_(I was unable to find any documentation for this in [README.md](https://github.com/jekyll/jekyll-admin/blob/master/README.md) or the [Jekyll Admin Docs](https://jekyll.github.io/jekyll-admin/). Appologies if this feature already exists and I just missed it)_

### Description:
It would be nice if we could change the path used for the jekyll admin frontend and api. The defaults `/admin` and `/_api` are fine most of the time, but it would be really useful if we could define these in _config.yml instead. 

For example, if your site already has an /admin page, the two would collide and you will not be able to access both jekyll admin and the page at the same time. In this case, having the ability to change `/admin` to `/jekyll-admin` instead would be invaluable.

For example, it could be provided in `_config.yml` as follows:

```yaml
jekyll_admin:
  # DEFAULTS 
  # path:     /admin
  # api_path: /_api

  # Example user configs:
  path:     /jekyll-admin
  api_path: /_jekyll-admin-api

  hidden_links:
    - posts
    - pages
```

### Tell us a bit about yourself:
* Version of JekyllAdmin I'm using: `0.7.0`
* Version of Jekyll I'm using: `3.6.2`
* Operating System: `Windows 10`
* Browser: `Chrome Version 62.0.3202.94 (Official Build) (64-bit)`
