### ISSUE TITLE
Updating config adds `posts` to the `collections` section

### ISSUE THREAD

**Issue by mertkahyaoglu** [jekyll/jekyll-admin#44]
Here are the steps to reproduce the issue.

1._config.yml includes the following content;

``` yaml
title: Your awesome title
collections:
  test:
    foo: bar
    output: true
```

2.Update the config (`collection` section must be present)

3._config.yml file now includes the following content;

``` yaml
title: Your awesome title
collections:
  posts:
    output: true
  test:
    foo: bar
    output: true
```

4.Delete the following lines;

``` yaml
posts:
  output: true
```

5.It deletes those lines from the file but the response to the front-end still has them.
