### ISSUE TITLE
Feature request: Custom collection labels

### ISSUE THREAD

**Issue by SmallhillCZ** [jekyll/jekyll-admin#493]
The label for the Sidebar field is taken from collection name, which is not always the best option. The label then cannot contain some special characters (due to filesystem limitations).

I propose a setting in _config.yml:

```yml
jekyll_admin:
  collections:
    posts:
      label: Blog posts ✉
```

**Comment by mertkahyaoglu** [comment]
I don't see how special characters are useful when it comes to collections. Could you give an example why you need this?

**Comment by SmallhillCZ** [comment]
Well one example is in the original post, using an emoji, however more serious example is that we would like to use our language which comes with plenty of special characters that are not filesystem/URL friendly.

**Comment by mertkahyaoglu** [comment]
That makes sense. Thanks for explaining it 👍

**Comment by ashmaroli** [comment]
I've been thinking about this..
Instead of defining a new property under `jekyll_admin` namespace, how about just looking for `ui_label` key in the collection's `metadata`?
```yml
# _config.yml

collections:
  staz:
    output: true
    ui_label: 'Stáž'
```
