### ISSUE TITLE
Does this work on gitlab pages

### ISSUE THREAD

**Issue by xiaodongzhao** [jekyll/jekyll-admin#591]
### Description:

I tried to add jekyll-admin to jekyll on gitlab.io pages, however, when I go to mysite.gitlab.io/admin, it returns 404: The page you're looking for could not be found.

### Tell us a bit about yourself:
Here is my Gem file:

```
source "https://rubygems.org"
ruby RUBY_VERSION

# This will help ensure the proper Jekyll version is running.
gem "jekyll", "4.0.0"

# Windows does not include zoneinfo files, so bundle the tzinfo-data gem
gem 'tzinfo-data', platforms: [:mingw, :mswin, :x64_mingw, :jruby]

gem 'jekyll-admin', group: :jekyll_plugins
```
.gitlab-ci.yml
```
image: ruby:2.4

variables:
  JEKYLL_ENV: production
  LC_ALL: C.UTF-8

before_script:
  - bundle install

test:
  stage: test
  script:
  - bundle exec jekyll build -d test
  artifacts:
    paths:
    - test
  except:
  - master

pages:
  stage: deploy
  script:
  - bundle exec jekyll build -d public
  artifacts:
    paths:
    - public
  only:
  - master

```

### Steps to reproduce:
1. change Gemfile to add jekyll-admin as shown above
2. Run and wait for gitlab CI/CD to finish
3. navigate to xxx.gitlab.io/admin, and it returns 404
