### ISSUE TITLE
Issue Report: Error in Fetching _config.yml with Jekyll Admin

### ISSUE THREAD

**Issue by kamyarothmanhamad** [jekyll/jekyll-admin#711]
### Description:

When serving my Jekyll site locally and accessing Jekyll Admin at `http://127.0.0.1:4000/admin/`, I encounter an error message stating "Error: Could not fetch the config."

### Tell us a bit about yourself:
* Version of JekyllAdmin I'm using: 0.11.1
* Version of Jekyll I'm using: 4.3.3
* Operating System: Windows 10
* Browser: Chrome

### Steps to reproduce:

1. Add the `jekyll-admin` plugin to the `_config.yml` file.
2. Serve the Jekyll site locally using `bundle exec jekyll serve`.
3. Navigate to `http://127.0.0.1:4000/admin/`.

### I expected the following:

Jekyll Admin should load properly and fetch the `_config.yml` file without any errors.

### But got the following, instead:

An error message is displayed: "Error: Could not fetch the config."

### Other details:

Below is the `_config.yml` file:

```yaml
title: Dahatû | داهاتوو
email: kurddahatu@example.com
description: "Dahatu Foundation"
baseurl: ""
url: "https://dahatu-foundation-kurd.github.io"
twitter_username: dahatu

# Build settings
remote_theme: just-the-docs/just-the-docs

# Just the Docs settings
search_enabled: true
aux_links:
  "Theme on GitHub":
    - "//github.com/just-the-docs/just-the-docs"

plugins:
  - jekyll-remote-theme
  - jekyll-feed
  - jekyll-admin
```

Error message in the browser's developer console:
```
Error: Could not fetch the config
```

Steps taken to troubleshoot:
1. Validated `_config.yml` using an online YAML validator.
2. Checked file permissions to ensure `_config.yml` is readable.

The `_config.yml` file is located at the root of the project, and the site is hosted on GitHub Pages, but the error occurs during local development.
